// Package config loads ssg.toml from the current working directory.
// The directory containing ssg.toml is the site root; all other paths
// in the config are resolved relative to it.
package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

// ConfigFile is the file ssg expects to find in CWD.
const ConfigFile = "ssg.toml"

// Config is the resolved site configuration.  Path fields are absolute by
// the time Load returns.
type Config struct {
	SiteURL         string `toml:"site_url"`
	SiteDomain      string `toml:"site_domain"`
	SiteTitle       string `toml:"site_title"`
	SiteAuthor      string `toml:"site_author"`
	SiteDescription string `toml:"site_description"`
	TwitterHandle   string `toml:"twitter_handle"`

	SiteRoot   string `toml:"-"` // populated from CWD at load time
	ContentDir string `toml:"content_dir"`
	ThemeDir   string `toml:"theme_dir"`
	PublicDir  string `toml:"public_dir"`
	DistDir    string `toml:"dist_dir"`

	PostsPerPage int   `toml:"posts_per_page"`
	ImageWidths  []int `toml:"image_widths"`
	FilterDrafts bool  `toml:"filter_drafts"`

	ChromaLight string `toml:"chroma_light"`
	ChromaDark  string `toml:"chroma_dark"`

	Socials []Social `toml:"socials"`
}

// Social is one entry in the site's social-links list.
type Social struct {
	Title string `toml:"title"`
	URL   string `toml:"url"`
}

// Load reads ssg.toml from CWD.  Returns a clear error if it isn't there.
func Load() (*Config, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return nil, err
	}
	path := filepath.Join(cwd, ConfigFile)
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("%s not found in %s — run `ssg init` to create one", ConfigFile, cwd)
		}
		return nil, err
	}

	var c Config
	if _, err := toml.DecodeFile(path, &c); err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	if c.SiteURL == "" {
		return nil, errors.New("site_url is required in ssg.toml")
	}

	c.SiteRoot = cwd
	c.ContentDir = resolve(cwd, c.ContentDir, "data")
	c.ThemeDir = resolve(cwd, c.ThemeDir, "theme")
	c.PublicDir = resolve(cwd, c.PublicDir, "public")
	c.DistDir = resolve(cwd, c.DistDir, "dist")

	if c.PostsPerPage <= 0 {
		c.PostsPerPage = 10
	}
	if len(c.ImageWidths) == 0 {
		c.ImageWidths = []int{400, 800, 1200, 1600}
	}
	if c.ChromaLight == "" {
		c.ChromaLight = "tokyonight-day"
	}
	if c.ChromaDark == "" {
		c.ChromaDark = "tokyonight-night"
	}

	return &c, nil
}

// Init writes a default ssg.toml in CWD.  Errors if one is already present.
func Init() error {
	if _, err := os.Stat(ConfigFile); err == nil {
		return fmt.Errorf("%s already exists", ConfigFile)
	}
	return os.WriteFile(ConfigFile, []byte(defaultTOML), 0o644)
}

const defaultTOML = `# ssg site configuration
# Generated by ` + "`ssg init`" + `.  Edit the values below and run ` + "`ssg build`" + `.

# Identity
site_url         = "https://example.com"
site_domain      = "example.com"
site_title       = "My Site"
site_author      = "Your Name"
site_description = "What this site is about"
twitter_handle   = "yourhandle"

# Paths (relative to this file)
content_dir      = "data"
theme_dir        = "theme"
public_dir       = "public"
dist_dir         = "dist"

# Behavior
posts_per_page   = 10
image_widths     = [400, 800, 1200, 1600]
filter_drafts    = true

# Syntax highlighting (any chroma style name)
chroma_light     = "tokyonight-day"
chroma_dark      = "tokyonight-night"

# [[socials]]
# title = "X"
# url   = "https://twitter.com/yourhandle"
`

// PostsDir is content/posts.
func (c *Config) PostsDir() string { return filepath.Join(c.ContentDir, "posts") }

// TemplatesDir is theme/templates.
func (c *Config) TemplatesDir() string { return filepath.Join(c.ThemeDir, "templates") }

// CSSEntry is the source CSS file passed to tailwindcss.
func (c *Config) CSSEntry() string { return filepath.Join(c.ThemeDir, "assets", "css", "global.css") }

// StaticDir is theme/assets/static.
func (c *Config) StaticDir() string { return filepath.Join(c.ThemeDir, "assets", "static") }

// FontsDir is theme/assets/fonts.
func (c *Config) FontsDir() string { return filepath.Join(c.ThemeDir, "assets", "fonts") }

// ImagesOutDir is dist/_images.
func (c *Config) ImagesOutDir() string { return filepath.Join(c.DistDir, "_images") }

func resolve(root, val, fallback string) string {
	if val == "" {
		val = fallback
	}
	if filepath.IsAbs(val) {
		return val
	}
	return filepath.Join(root, val)
}
